version: "3.8"

services:
  tests:
    build: .
    container_name: all-tests
    command: ["pytest", "tests", "--alluredir=allure-results"]

  allure-server:
    image: "frankescobar/allure-docker-service"
    container_name: allure-server
    ports:
      - "5050:5050"
    environment:
      CHECK_RESULTS_EVERY_SECONDS: 3
      KEEP_HISTORY: 1
    volumes:
      - ./allure-results:/app/allure-results